#!/bin/bash
user=$(whoami)
#Checking for user permissions
if [ "$user" != "root" ]; then
echo ${red}"This program must be run as root ${textreset}"
echo "Exiting"
exit
else
echo "Running Program"
fi

items=(1 "Add MAC Address for Auth"
       2 "Delete MAC Address from Auth"
       3 "Add MAC Address for Auth with iPSK"
       4 "Delete MAC Address with iPSK from Auth"
       5 "Start FreeRADIUS Service"
       6 "Stop FreeRADIUS Service"
       7 "Restart FreeRADIUS  Service"
       8 "FreeRADIUS Service Status"
       9 "Debug Mode -radiusd -X-"
      10 "AD Connector Diag"
      11 "Test PEAP/MSCHAP"
)

while choice=$(dialog --title "$TITLE" \
                 --backtitle "FreeRADIUS Service Management" \
                 --menu "Please select" 20 50 3 "${items[@]}" \
                 2>&1 >/dev/tty)
    do
    case $choice in
        1)/root/.servman/FRManager/create-mac-auth-entry;;
        2) /root/.servman/FRManager/delete-mac-auth-entry;;
        3)/root/.servman/FRManager/create-mac-auth-entry-ipsk;;
        4)/root/.servman/FRManager/delete-mac-auth-entry-ipsk;;
        5) /root/.servman/FRManager/start-freeradius-server;;
        6) /root/.servman/FRManager/stop-freeradius-server;;
        7) /root/.servman/FRManager/restart-freeradius-server;;
        8) /root/.servman/FRManager/service-freeradius-status;;
        9) /root/.servman/FRManager/debug-freeradius;;
        10) /root/.servman/FRManager/debug-ad-connector;;
        11) /root/.servman/FRManager/fr-peap-mschap-test;;
        *) ;; # some action on other
    esac
done
clear # clear after user pressed Cancel
