#!/bin/bash
user=$(whoami)
#Checking for user permissions
if [ "$user" != "root" ]; then
echo ${red}"This program must be run as root ${textreset}"
echo "Exiting"
exit
else
echo "Running Program"
fi

items=(1 "FreeRADIUS Management"
       2 "System Management"
       3 "Server Management Options"
       4 "System Tools"
       5 "Welecome to Server Manager"
)

while choice=$(dialog --title "$TITLE" \
                 --backtitle "Server Management" \
                 --menu "Please select" 20 40 3 "${items[@]}" \
                 2>&1 >/dev/tty)
    do
    case $choice in
        1) /root/.servman/FRMan;;
        2) /root/.servman/SYSMan;;
        3) /root/.servman/SERVMan;;
        4) /root/.servman/TOOLMan;;
        5) /root/.servman/welcome.readme;;
    esac
done
clear # clear after user pressed Cancel
