#!/bin/bash
#Update Server Manager
clear
cd /root/
dnf -y install wget
wget https://raw.githubusercontent.com/fumatchu/FR-RADS-SM/main/FR-RADS-SMInstaller.sh
chmod 700 ./FR-RADS-SMInstaller.sh
/root/FR-RADS-SMInstaller.sh
