#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}FreeRADIUS Server Management${TEXTRESET}
${GREEN}Delete MAC Auth Entry${TEXTRESET}
EOF

read -p "Please input the mac address ${YELLOW}without special characters, and lowercase${TEXTRESET} (i.e.00b0d063c226): " MACADDR

sed -i "/^$MACADDR/{n;d}" /etc/raddb/mods-config/files/authorize
sed -i "/$MACADDR/d" /etc/raddb/mods-config/files/authorize

echo "You Must Restart the FreeRADIUS Server for the changes to take effect"

while true; do
   read -p "Would you like to restart the service now? (y/n) " yn
   case $yn in
   [yY])
      echo ${GREEN}"Restarting FreeRADIUS${TEXTRESET}"
      sleep 1
      systemctl restart radiusd
      break
      ;;
   [nN])
      echo ${RED}"Cancelled${TEXTRESET}"
      sleep 1
      exit
      ;;
   *) echo invalid response ;;
   esac
done
exit
