#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}FreeRADIUS Server Management${TEXTRESET}
${GREEN}Testing Login with MS-CHAP${TEXTRESET}
EOF

read -p "Please provide the AD username to emulate logging in from a client: " ADUSER
read -p "Please provide the AD user's Password: " ADUSERPASS
clear
cat <<EOF
${GREEN}Testing User login with MS-MPPE${TEXTRESET}

EOF
radtest -t mschap $ADUSER $ADUSERPASS localhost 0 testing123

read -p "Press Any Key" 
