#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}FreeRADIUS Server Management${TEXTRESET}
${GREEN}Query for MAC Address${TEXTRESET}

EOF
read -p "Provide the MAC Address (i.e. 00b0d063c221) or description to search: " QUERY

echo "Result:"

more /etc/raddb/users | grep $QUERY -C2
cat  << EOF

${RED}Note- The Description is UNDER the MAC address Entry${TEXTRESET}

EOF
read -p "Press Any Key to Continue"
