#!/bin/bash
#Checking for user permissions
user=$(whoami)
if [ "$user" != "root" ]; then
   echo ${red}"This program must be run as root ${textreset}"
   echo "Exiting"
   exit
else
   echo "Running Program"
fi
textreset=$(tput sgr0)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
green=$(tput setaf 2)
maclower=$($MACADDR | sed -e 's/\(.*\)/\L\1/')
clear
cat << EOF
${red}FreeRADIUS MAC QUERY${textreset}
${yellow}Query MAC Auth Entry${textreset}

EOF

read -p "Provide the MAC Address (i.e. 00b0d063c221) or description to search: " QUERY

echo "Result:"

more /etc/raddb/users | grep $QUERY -C2
cat  << EOF
Note- The Description is UNDER the MAC address Entry
EOF
read -p "Press Any Key to Continue"
