#!/bin/bash
TEXTRESET=$(tput sgr0)
RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
USER=$(whoami)

#Checking for user permissions
if [ "$USER" = "root" ]; then
echo " "
else
  echo ${RED}"This program must be run as root ${TEXTRESET}"
  echo "Exiting"
fi
clear
cat << EOF
${GREEN}FreeRADIUS Server Management${TEXTRESET}
${GREEN}Renew Certificates${TEXTRESET}

EOF
cat <<EOF
This will generate extended certificates for testing purposes.
If you are going to run this server in production, you should be installing
valid certificates on this server from a valid cert authority

Please type "y" if you want to proceeed
EOF




while true; do

read -p "I understand the ramifications of using testing certs for 802.1x on this server  (y/n) " yn

case $yn in
        [yY] ) echo ${GREEN}" Updating Certificates ${TEXTRESET}";
                break;;
        [nN] ) echo echo ${RED}"Cancelled${TEXTRESET}";
                exit;;
        * ) echo invalid response;;
esac

done


#create new certs
/etc/raddb/certs/bootstrap

echo ${RED}"Stopping and starting services${TEXTRESET}"
sleep 1
systemctl stop radiusd
systemctl start radiusd
systemctl status radiusd
read -p "Press Any Key"
echo ${GREEN}"Certificates Updated${TEXTRESET}"
echo " "
read -p "Press Any Key"
