#!/bin/bash
#Checking for user permissions
user=$(whoami)
if [ "$user" != "root" ]; then
echo ${red}"This program must be run as root ${textreset}"
echo "Exiting"
exit
else
echo "Running Program"
fi
textreset=$(tput sgr0)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
green=$(tput setaf 2)

clear
cat  <<EOF
${green}Starting FreeRADIUS${textreset} Service
EOF
systemctl start radiusd
ps -ax | grep radiusd | head 
sleep 1 

read -p "Press Any Key" 

systemctl status radiusd

read -p "Press Any Key"

